### PR TITLE
Adding on to Tree Solution

### PR DESCRIPTION
**Pull request by eric-chahin**
Things left to fix (that I know of):

1. Constructor should be a bit smarter about its arguments and throw exceptions if it doesn't make sense.
2. I believe swap is correct, unless it is meant to recurse. There was a lot of time spent learning about C++ references.
3. Not exactly sure the best way to test for print with the OSTREAM.
4. The destructor was freeing memory too soon, so this needs to be fixed.

### CODE REVIEW

**Comment by pkambadu** [comment]
The whole point about smart pointers is that you don't have to explicitly free memory. There must be some other bug. Maybe you are trying to free something allocated on the stack instead of the heap?

**Comment by eric-chahin** [comment]
Okay, I will take a deeper look into the boost libraries and try to figure out if there are any memory leaks.

Anju, just a specification question: should we also throw exceptions depending on the info/structure of the tree? I thought we were trying to make this tree as generic as possible, so that is why we didn't do the explicit checks for the operators.

Also, could you take a look at our swap method? We think that swap should just be swapping the individual data members of the root node. Is that correct? 
Chetan's group seems to have some recursive method going on (without a base case) for swap, but when I tried that out it wasn't properly recursing.

**Comment by hamsal** [comment]
Hey Anju, the recursive implementation of swap in the other PR is not meant to be recursive if you look at what I commented there, so both of these implementations should agree.

**Comment by pkambadu** [comment]
Let me take a look tomorrow

**Comment by hamsal** [comment]
There is now a test for ExpressionTree that will fail until mirror equality is implemented with commutative operators in mind. There is also a test for Tree designed to enforce that no mirror equality should be considered at the base Tree.

**Pull request merged**
