### PR TITLE
[WIP] Move parser source from hpp to cpp

### PR DESCRIPTION
**Pull request by hamsal**
- [x] Move as much code to cpp as possible
- [x] Include function profiles in the hpp
- [x] ```detail``` namespace to hide internal library code
- [x] Move all structs in the header file 
- [ ] doxygen documentation
- [x] 80 character format
- [x] Do not indent after namespace
- [ ] rename expr to binop
- [ ] re factor to make unary op
- [ ] define constructors outside of struct declerations

### CODE REVIEW

**Comment by eric-chahin** [comment]
That's a awesome class but that's not how you should do it :stuck_out_tongue_winking_eye:

**Comment by hamsal** [comment]
This pull request compiles for me, To test if pull requests compile you can get the code using the button shown here. https://help.github.com/articles/checking-out-pull-requests-locally/
image

**Comment by hamsal** [comment]
I updated the parser to include expression hpp instead of expression cpp

**Comment by hamsal** [comment]
This is a partial update to create the '''detail''' namespace and to app some declarations to hpp

**Comment by pkambadu** [comment]
Hey Hamzeh --- This is great work. So, some comments:

(1) Look at how  we want to name classes and variables in the wiki.
(2) Refactor negate_expr, transpose_expr, and inv_expr into UnaryOp.
(3) You need to move the "definition" of the constructors outside the structure definitions --- in the case of parser, expr, etc, this will be moved to the bottom of the expression.hpp file.

**Pull request closed without merging**
