### PR TITLE
Fixes for Current Assignment on Wiki

### PR DESCRIPTION
**Pull request by eric-chahin**

### CODE REVIEW

**Comment by pkambadu** [comment]
0. General comments:
   - We use camel case for variables (`fooBar` instead of `foo_bar`).
   - We use `d_` prefix for member variables (`d_fooBar` if its a member variable).
   - Clean up any print out statements you might have.
   - Think hard about where certain methods should belong and how they should function carefully.
   - Write extensive output to logs. This is your salvation.
   - Be consistent about exceptions --- always throw AMD exceptions.
   - The order of the header includes should be:
        1. Standard header such as `iostream` or `string`.
        2. Library headers such as `boost/foobar.hpp`.
        3. Internal headers such as `AMD/foobar.hpp`.

1. `expression.cpp`, `expression.hpp`, `expression.t.cpp`: 
  - Always have the standard headers such as `<string>`, before the AMD headers. Just good practice.
  - There is at least one spurious `std::cout`, maybe more. Remember, there should be no print outs from the library files --- only log messages.
  - More logging messages.
  - `compareExpectedExpressions` should not be something in expression.cpp --- it is only for tests. So, move it into `expression.t.cpp`.
  - Why aren't you using AMD's exceptions in `compareExpecctedExpressions`?
  - Think about comparing the expressions without the spaces ... it might be of help in the future.
  - More test cases to cover all precedence for operators.
  - More test cases to cover `lgdt` and `tr`.

2. `expressiontree.cpp`, `expressiontree.t.cpp`:
  - `logging_enabled` should be named `loggingEnabled` -- we use camel case throughout but for the prefix `d_` for the class members.
  - What we want to check for is not if logging is enabled. The point is that regardless of whether logging is enabled or not, we want to throw exceptions only if we are not using `ExpressionTree` in parser. This should be a boolean member variable --- `d_throwExceptions` that is default initialized to `false`. Logging is separate from throwing exceptions. A sample code would be:

```c++
if (!(left) || (right)) {
    LOG_ERROR << "Some error";
    if (d_throwExceptions) {
        throw AMD::ExceptionImpl(...);
   }
}
```
  - How is `operator==` in `ExpressionTree` different from that of `Tree`? I can see why you would need this. For example, for commutative operations, two subtrees are equal even if `this->left==other->right`  and `this->right==other->left`. However, there are very few commutative operations for matrices. Remember that matrix multiplication is commutative only under special circumstances.
 - You only need one `AMD_START_TRY_BLOCK`, `AMD_END_TRY_BLOCK`, and other such macros per function. In `expressiontree.t.cpp`, I see that there are multiple ones.

3. `matrixgrammar.hpp`:
  - I haven't taken a close look yet and we can talk about it during our meeting, but please call `d_basis` as `d_literal` or something similar. Remember, as time passes, the effort you put into commenting, into pick descriptive variable names. 
  -  Let us talk more about this during our meeting.

**Comment by hamsal** [comment]
I re implemented Erics d_litteral rule which was reverted to debug.

**Comment by hamsal** [comment]
I am trying to implement trace and logdet using operators that are multiple characters but boost gives me the warnings below and fails to compile.

Here is the offending code:

```  C++
    d_factor =
            d_literal                        [qi::_val = qi::_1]
       |   '(' >> d_expression               [qi::_val = qi::_1] >> ')'
       |   ('-' >> d_factor                  [neg(qi::_val, qi::_1)])
       |   ('+' >> d_factor                  [qi::_val = qi::_1])
       |   ('tr(' >> d_factor                [trace(qi::_val, qi::_1)] >> ')')
       |   ('lgdt(' >> d_factor              [lgdt(qi::_val, qi::_1)] >> ')')
       ;
```

and one of the warnings

``` 
/home/hamzeh/Dropbox/desktop/Repos/AMD-eric/AMD/AMD/matrixgrammar.hpp:277:13: warning: multi-character character constant [-Wmultichar]
/home/hamzeh/Dropbox/desktop/Repos/AMD-eric/AMD/AMD/matrixgrammar.hpp:278:13: warning: character constant too long for its type [enabled by default]

```

It looks like its saying to add a compiler flag.

**Comment by hamsal** [comment]
side note looking at the parser precedence as I posted it, I don't think its correct

**Comment by hamsal** [comment]
Fixed it, I was using single quotes around a string. I implemented trace and logdet.

**Comment by hamsal** [comment]
Bug: The parser works on ```tr((A+B))``` but not ```tr(A+B)```

**Comment by pkambadu** [comment]
Wait so there is still a bug?

**Comment by hamsal** [comment]
I implemented a function so that the string `(A+B)'_'` gets converted to the string `trans(inv(trans(A+B)))` and I updated the parser to parse `inv(` `)` and `tran(` `)` operators so that now expressions like `A'_'` get parsed correctly to `(' (_ (' "A")))`

**Comment by ahillhouse** [comment]
I figured out that the problem with repeated inverse and transpose is that this particular type of parser doesn't support left recursion because it makes it segfault.  I think Hamzeh came up with an awesome solution that doesn't require us to make major changes to the grammar as it is right now! :+1:

**Comment by eric-chahin** [comment]
I agree with Amber and say that Hamzeh's solution is the best! I tried to do a fix for the left recursion problem (mentioned: http://en.wikipedia.org/wiki/Left_recursion#Pitfalls) and couldn't get the parsing to work correctly, look presentable, and in the right order. His preprocessing is simple and readable. 
Two thumbs up from me! :+1: :+1:

**Comment by pkambadu** [comment]
Hey Folks,

Looks like lots of progress has been made. Good work! I am still in
Istanbul, but am back in NYC tomorrow around 1:00 PM. I can meet with you
all on Tuesday instead of tomorrow. Alternately, if you give me a pull
request with detailed comments, I can comment on it tomorrow and you can
look at it on Tuesday.

One comment (ignore if you have done this already):
Make sure that the new fix did not break any old code. Primarily, this
means running the regression tests. Maybe adding some new tests as well.

Looks like we are finally close to starting differentiation of matrices.

Anju

**Comment by pkambadu** [comment]
Accepting these for now. There are errors still that the folks are working on.

**Pull request merged**
