### PR TITLE
Merged tree implementation - Chetan, Eduardo, Hamzeh

### PR DESCRIPTION
**Pull request by hamsal**
Contains work for developing the Tree with appropriate testing and documentation. Online and offline colaboration by Chetan, Eduardo, and Hamzeh

- [x] Create empty structure for the testing file
- [ ] Test: debug Tree test
- [ ] Test: ~Tree
- [ ] Test: debug swap test
- [x] Test: ==
- [ ] Test: !=
- [ ] Test: info
- [ ] Test: setInfo
- [ ] Test: print 
- [x] Implement: Tree
- [ ] Implement: Constructor Parameter Checking
- [ ] Implement: ~Tree
- [x] Implement: swap
- [x] Implement: ==
- [x] Implement: !=
- [x] Implement: info
- [x] Implement: setInfo
- [ ] Implement: print 
- [ ] Write documentation

### CODE REVIEW

**Comment by cg439** [comment]
We basically merged into a new pull request so that all our changes to the branch in hamzeh's repo automatically get merged together in this pull request. Will be updating progress as we go through and implement the tree/debug test cases/debug implementation

**Comment by pkambadu** [comment]
So, this contains all of your changes, correct? This is the only pull
request that I should look at from your team.

Anju

**Comment by hamsal** [comment]
That is correct

**Comment by pkambadu** [comment]
Ok good. Let me know if I am missing something. I'll take a look at it
today. Some immediate comments:

(1) Indentation is off :).
(2) operator==() has bugs. Look at the thread between me and Amber for more
information. I posted some *more or less* working code there.

**Comment by hamsal** [comment]
Hey Chetan and Anju this is a question for both of you. I am looking at the constructor implemented in this PR and see the value in how Chetan wrote it to enforce the invariant of the mathematical structure of what is being parsed. Is this tree intended to have this feature or is it meant to be general and free of those assumptions?

**Comment by hamsal** [comment]
Hey Chetan, I think I figured out our SIGABRT bug. an empty `throw;` essentially causes termination of the program and it can not be caught. http://stackoverflow.com/questions/5378677/what-does-a-single-throw-statement-do

On top of that I caught a bug in the constructor where `d_info` was being used where `info` was probably meant to be.

**Comment by pkambadu** [comment]
Sorry guys --- I'll take a look at this tomorrow afternoon. My day is
packed till then.

**Comment by cg439** [comment]
Hey Hamzeh, didn't get a chance last night but will check today after class how to resolve the issue, thanks didn't realize that is what happened. I think then we just need to say throw an exception so it knows what to throw, so either some error code with throw or throwing a specific exception class. Will try and see if either resolves the issue.

**Comment by pkambadu** [comment]
Or throw an std::exception. I'm going to put in exceptions today and try to
write a wiki on how to use them.

**Comment by cg439** [comment]
I changed the throw; statements into throw std::runtime_error("invalid parameters"); Will fix the exact error message later, for now trying to debug why no runtime error is thrown by the tests. It gives a message stating it expected a certain exception but it was never thrown. I looked up and found that this message only occurs when no exception was thrown. If another exception was thrown it would say something to the effect of incorrect exception caught. Will try looking into what could be incorrect with my logic in the constructor for invalid parameters

**Comment by pkambadu** [comment]
Hey Folks --- The test cases (both promised in the comments and those implemented) look good. Please take a look at exception.hpp and exceptions.t.cpp to find out how you can use the macros I have created instead of having your own try and catch blocks. In particular, look at the top of exception.hpp to see all the different error codes you can throw for invalid operations, and at exceptions.t.cpp to see how you can throw and rethrow from deep within the library and have those errors propagate up. Just run exceptions and you'll see the nice information printed out.

Let me know if you have any trouble following the code. I would not delve too much into the actual implementation itself. Two points:

(1) Check to make sure that the indentation is nice
(2) Please close all requests that you don't want me to look at. I currently have 4 open requests from your group --- I think Hamzeh closed a couple. At the end of the day, I should be looking at tree.hpp, tree.cpp, and tree.t.cpp --- three files. 

If you have already closed the unwanted requests, I apologize for not having seen it properly. 

Keep up the good work!

**Comment by hamsal** [comment]
I can see the confusion about how I wrote `swap`. I am under the impression that doing `this->d_left.swap(other.d_left);` is calling the swap function for the shared pointer not for the tree. 
http://www.cplusplus.com/reference/memory/shared_ptr/swap/

**Pull request closed without merging**
