### PR TITLE
Add functionality to tree constructor, ==, and !=

### PR DESCRIPTION
**Pull request by ahillhouse**
Contains functionality for binary tree by Amber and Eric.

- [ ] Test: swap
- [x] Test: ==
- [x] Test: !=
- [ ] Test: info
- [ ] Test: setInfo
- [ ] Test: print
- [x] Implement: Tree
- [ ] Implement: ~Tree
- [ ] Implement: swap
- [x] Implement: ==
- [x] Implement: !=
- [ ] Implement: print

### CODE REVIEW

**Comment by ahillhouse** [comment]
Would you prefer me to keep it within the function?  My rational for taking it out is that it does not require all of those checks and thus reduces the calculations done by a constant factor and especially if you need to check for equality of very large trees, then this would make it a lot faster.

**Comment by ahillhouse** [comment]
Ahh I see what you're saying.  For me it was more clear to split it into two functions but I will put them into one if that's how you'd prefer it.

**Comment by pkambadu** [comment]
Check my latest post ... Let's keep the posting's there so that others can
also see.

Anju

**Comment by pkambadu** [comment]
Here is a mostly bug-free version --- can you spot any bugs? Also, can you spot any differences from your code?

```c++
bool operator(const Tree& other) 
{
   // Return if the information is not equal
   if (this->d_info != other.d_info) return false;

   // If information is equal and so are the left and right pointers, we can return
   if ((this->d_left == other->d_left) && (this->d_right == other.d_right)) return true;

   // Check if one of the pointers is empty. If both were empty, we would have 
   // caught it at the previous check point.
   if (!this->d_left  || !other.d_left) return false;
   if (!this->d_right || !other.d_right) return false;
  
   // Recursive subtree checks
   if (!(*(this->d_left)==other.d_left)) return false;
   if (!(*(this->d_right)==other.d_right)) return false;

   return true;
}
```

**Comment by ahillhouse** [comment]
Good catch - I actually just meant to call Tree::equal recursively.  I pushed a fix for that.

**Comment by pkambadu** [comment]
Since the left and right children are held as shared pointers, it is never intended to create any tree node on the stack --- everything must be allocated on the heap. So, from the very first node you create, you can use ```boost::make_shared<Tree>("NODE STRING INFO")``` and store it in a ```boost::shared_ptr<Tree>```. Once a tree node has been created on the stack, there is no way to make it into a shared pointer without having to copy construct a new one.

**Comment by pkambadu** [comment]
I am still uncomfortable with a method called ```Tree::equal```. Something does not sound right. You are welcome to factor the equality check into a sub-function as long as you use an overloaded ```operator==``` (see previous post about that) or just write everything in one function.

**Comment by ahillhouse** [comment]
I will move it into one function.

And I see - then we should never be creating just a Tree; Everything should be a shared pointer from its creation and then just de-referenced to use these functions, right?

**Comment by pkambadu** [comment]
Right  about the shared pointer question. Read up the difference between heap and stack allocation when you get a chance.

**Comment by ahillhouse** [comment]
Also, the bug in your sample code will occur when both trees have a null child on one side but neither have a null child on the other.

**Comment by pkambadu** [comment]
That might be. Can you explain further? Either way, I hope this tells you how hard it is to right *correct* code :). All of the cases that you are thinking about now --- things that can go wrong --- those are the cases that you should write tests for.

**Comment by ahillhouse** [comment]
The code checks if BOTH sets of children nodes are null, or if one pair of children has only a single null node, but when both trees have a null child on one side and not a null child on the other, that does not fit either of those cases.  You would get an error when trying to dereference the null children.

**Pull request closed without merging**
